print('\n')
print('#','#', sep='\t\t')
print('#','#', sep='\t\t')
print('#########')
print('#','#', sep='\t\t')
print('#','#', sep='\t\t')
print('\n')
print('#########')
print('#','#', sep='\t\t')
print('#','#', sep='\t\t')
print('#','#', sep='\t\t')
print('#########')
print('\n')